### ISSUE TITLE
Plugin not working anymore? Firefox 113.0.2

### ISSUE THREAD

**Issue by MarkoH01** [poacher2k/gog-2nd-class-ext#1]
I noticed that the second class plugin does not seem to work anymore. I tried it on the store page for Seven and A Hat in Time. Both are games that are missing updates but nothing the plugin does not mark the issues on the gamecard. To be certain that it is not one of my other scripts interfering with this one I even disabled them all - unfortunately without any success.

**Comment by poacher2k** [comment]
Strange! Might be something with the caching (https://github.com/poacher2k/gog-2nd-class-ext/blob/main/src/utils/getData.ts#LL24C4-L24C4) - should clear itself in < 24hrs, but I'll look into fixing the bug too. 

(still works for me) 
<img width="704" alt="image" src="https://github.com/poacher2k/gog-2nd-class-ext/assets/2255960/724884a0-2b62-47c1-9af1-300ce731695a">

**Comment by MarkoH01** [comment]
Thank you for the quick reply :)

A friend of mine just realized where the problem is. GOG localized the URLs a while ago. So for this URL
https://www.gog.com/game/seven_the_days_long_gone
The plugin is working, but me being from Germany the URL GOG normally is offering for me is
https://www.gog.com/en/game/seven_the_days_long_gone
And here the plugin is not working.

**Comment by poacher2k** [comment]
Ohh, shoot, well that's an easy fix at least! Thank you and your friend for reporting and debugging it!

**Comment by MarkoH01** [comment]
Easy fix sounds great for me :D
No need to thank me (or us), I have to thank you for the great plugin.

**Comment by poacher2k** [comment]
@MarkoH01 : Fixed! Should update itself automatically, or you can go to `about:addons` -> Click the cog wheel up top -> Check for updates :)

**Comment by MarkoH01** [comment]
Works perfectly. Thanks again for the quick fix :)
