### ISSUE TITLE
Achievement table

### ISSUE THREAD

**Issue by eirnym** [poacher2k/gog-2nd-class-ext#2]
The linked table has another table linked specifically for achievements. Could you please to include it as well?

**Comment by poacher2k** [comment]
Good idea! I'll look at this when I get some free time 👍🏻

**Comment by poacher2k** [comment]
@eirnym : Found some time! Update coming :)

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/78b015eb-a3ea-494e-b41f-31c2dea18d47">

**Comment by poacher2k** [comment]
New version (2.2) is now live!

**Comment by eirnym** [comment]
Just updated, works like a charm! Thank you
